### ISSUE TITLE
External Index Empty

### ISSUE THREAD

**Issue by DavidArmitage** [callumbwhyte/examine-facets#5]
Hi,

I managed to get facets working but it has broken everything else. Facets searching is finding that there's data related to the categories.

Unfortunately all my other examine searches are bringing back no data after re--building the search index.
I am guessing this is related to upgrading from Examine 1.0.1 to 1.0.3

I am not sure how to get this fixed. I noticed there is an updated version of Examine so I am attempting to upgrade to 1.0.6 to see if this fixes the issues.

**Comment by DavidArmitage** [comment]
The upgrade seems to have fixed that.
I am not sure at all what happened there. Scary for a minute.

**Comment by callumbwhyte** [comment]
Hey @DavidArmitage,

Glad to hear the upgrade fixed this for you! 👍

Callum
