### ISSUE TITLE
Umbraco 8.12 uses examine 1.1.0

### ISSUE THREAD

**Issue by soreng** [callumbwhyte/examine-facets#8]
Hi @callumbwhyte ,

I can see you already have a branch for examine 1.1.0. With the release of Umbraco 8.12, we would love for a new version of Examine.Facets please :)

Can we help in any way?

**Comment by callumbwhyte** [comment]
Hey @soreng,

Thanks for your excitement about Examine Facets!

Yes there is a v1.1.0 branch. The only reason this has been held up is I need to find time to confirm that ManagedQuery works, previously calling `ManagedQuery` would return the search back to the default searcher. Any help here would be cool, but I may find time this weekend :-)

As for running with Umbraco v8.12, Examine Facets should still work as there are no breaking changes.

Cheers,
Callum

**Comment by callumbwhyte** [comment]
Hey @soreng!

v1.1.0 is now available from all good package repositories! Happy Faceting.

Cheers,
Callum
